### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by martinhanes** [abmantis/homeassistant-custom-components#11]
Hi @abmantis  :-) 

First of all, thanks for a great piece of code for HA custom component :-) 

I wanted to know whether you were aware of the Whirlpool side API change that caused the plugin to stop functioning properly.

Martin

**Comment by abmantis** [comment]
Hey. Yes, I know it changed (see https://github.com/home-assistant/core/issues/69602 ). Unfortunately I don't have the Whirlpool AC installed so it is not that easy for me to work on it. If someone else could reverse eng. the new API, I would gladly help adapting the lib for it.

Anyway, the whirlpool custom component here is deprecated since it is already in the official HA repo.
